// Debate Search Types

export const ADD_SEARCH_LOCAL_STATE = "ADD_SEARCH_LOCAL_STATE";
export const REMOVE_SEARCH_LOCAL_STATE = "REMOVE_SEARCH_LOCAL_STATE";
export const ADD_LOADING_LOCAL_STATE = "ADD_LOADING_LOCAL_STATE";
export const REMOVE_LOADING_LOCAL_STATE = "REMOVE_LOADING_LOCAL_STATE";

//  SEARCH Types

export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const REMOVE_SEARCH_REQUEST = "REMOVE_SEARCH_REQUEST";

export const SEARCH_REQUEST_ERROR = "SEARCH_REQUEST_ERROR";
export const REMOVE_SEARCH_REQUEST_ERROR = "REMOVE_SEARCH_REQUEST_ERROR";
